/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package drawerControllib;

class DrawerControlJNI {
  public final static native void openCommunication() throws java.lang.Exception;
  public final static native void closeCommunication() throws java.lang.Exception;
  public final static native void openDrawer() throws java.lang.Exception;
  public final static native int getStatus() throws java.lang.Exception;
}
