/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package drawerControllib;

public class DrawerControl {
  public static void openCommunication() throws java.lang.Exception {
    DrawerControlJNI.openCommunication();
  }

  public static void closeCommunication() throws java.lang.Exception {
    DrawerControlJNI.closeCommunication();
  }

  public static void openDrawer() throws java.lang.Exception {
    DrawerControlJNI.openDrawer();
  }

  public static Status getStatus() throws java.lang.Exception {
    return Status.swigToEnum(DrawerControlJNI.getStatus());
  }

}
